- hosts: node
  become: yes
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  tasks:
    - name: Stop service node, if started
      service:
        name: nodeapp
        state: stopped
